name: Publish to GitHub Pages

on:
  push:
      branches:
        - wasm
  workflow_dispatch:

jobs:
  deploy:
    concurrency: ci-${{ github.ref }} 
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          components: rustc, cargo
      - name: Install `cargo-binstall` Command
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install Trunk
        run: cargo binstall --locked --no-confirm trunk 
      - name: Compile WASM Site
        run: trunk build --release
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist      
